description: >
  This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here.
  If you do not require an executor, you can simply delete this directory.
docker:
  - image: 'cimg/php:<<parameters.tag>>'
parameters:
  tag:
    default: 8.0-node
    description: >
      Pick a specific cimg/php image variant:
      https://hub.docker.com/r/cimg/php/tags
    type: string
